### ISSUE TITLE
Size hook status reports to the width of the terminal

### ISSUE THREAD

**Issue by sds** [sds/overcommit#147]
When displaying the results of a hook run, it would be nice if the output automatically expanded/contracted to fit the width of the terminal.

If the output stream is not a TTY, we should fall back to a default width of 80 characters.

**Comment by jawshooah** [comment]
I assume this is limited to messages generated by Overcommit, right? We don't want to truncate hook error/warning messages, lest we hide important information from the user.

**Comment by sds** [comment]
Right, this is intended affect the hook status messages so that the statuses appear at the rightmost edge of the terminal, i.e. all the "OK"s line up against the very edge.

```
Checking Gemfile dependencies...........................[BundleCheck] OK
Validating JSON syntax...................................[JsonSyntax] OK
Checking for local paths in Gemfile.............[LocalPathsInGemfile] OK
Analyzing with Rubocop......................................[Rubocop] OK
Checking for trailing whitespace.................[TrailingWhitespace] OK
Checking Travis CI configuration.........................[TravisLint] OK
Checking YAML syntax.....................................[YamlSyntax] OK
```

It might not be worth putting too much effort into this just yet considering #144 may completely change how we think about displaying statuses. At the same time perhaps there is some useful work that can be done here to abstract away having to differentiate between a TTY and a regular file output stream.
