### ISSUE TITLE
Should fail loudly when a custom hook specified via configuration cannot be found

### ISSUE THREAD

**Issue by gms8994** [sds/overcommit#325]
I have a `.overcommit.yml` file that looks like this:

``` yaml
plugin_directory: .git_hooks/pre_commit

PreCommit:
  PhpCs:
    enabled: true  # All custom hooks are disabled by default.
    description: Verifies code formatting is acceptable # Prints a description when your hook is run.
    phpcs: /Users/glens/.composer/vendor/bin/phpcs  # Setting the max length to 89 chars. Accessed through the `config` attribute in our hook.
    standard-file: ~/phpcs.xml
    inclues: 
      - '**/*.php'
```

and `overcommit -l` shows the following:

``` yaml
PreCommit:
  AuthorEmail: enabled
  AuthorName: enabled
  BerksfileCheck: disabled
  Brakeman: disabled
  <snip ...>
  PhpCs: enabled
```

And the file in `.git_hooks/pre_commit/PhpCs.rb`:

``` ruby
require 'json'

module Overcommit::Hook::PreCommit
    class PhpCs < Base
        def run
            error_lines = []
            warning_lines = []

            phpcs_location = config['phpcs']
            standard_file = config['standard-file']

            applicable_files.each do |file|
                report_json = `#{phpcs_location} --standard=#{standard_file} --report=json`

                report = JSON.parse(report_json)
                report['files'].each do |filename, object|
                    object['messages'].each do |message|
                        message << format("#{filename}@#{message['line']}:#{message['column']} - #{message['message']}")
                        if message['type'] == 'ERROR'
                            error_lines << message
                        else
                            warning_lines << message
                        end
                    end
                end
            end

            return :fail, error_lines.join("\n") if error_lines.any?

            return :warn, warning_lines.join("\n") if warning_lines.any?
        end
    end
end
```

Running `overcommit -r` doesn't list it as being run:

``` sh
overcommit -r
Running pre-commit hooks

✓ All pre-commit hooks passed
```

Is there a reason it says enabled, but doesn't run?

**Comment by sds** [comment]
Try changing your `plugin_directory` to just `.git_hooks`. Overcommit will search for `pre_commit`/`pre_push` etc directories under that directory.

When you list hooks with `overcommit -l`, it's just showing the hooks you have configured in your `.overcommit.yml`. 

I think this something Overcommit can do a better job warning you about. We should fail loudly when we can't find a configured hook.

**Comment by gms8994** [comment]
Thank you for the quick response. Once I adjusted the plugin_directory, I get the following:

```
/Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/hook_signer.rb:52:in `signable_file?': undefined method `start_with?' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/hook_signer.rb:38:in `hook_path'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/hook_signer.rb:92:in `hook_contents'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/hook_signer.rb:88:in `signature'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/hook_signer.rb:61:in `signature_changed?'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/hook_loader/plugin_hook_loader.rb:51:in `select'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/hook_loader/plugin_hook_loader.rb:51:in `modified_plugins'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/hook_loader/plugin_hook_loader.rb:55:in `check_for_modified_plugins'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/hook_loader/plugin_hook_loader.rb:8:in `load_hooks'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/hook_runner.rb:146:in `load_hooks'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/hook_runner.rb:28:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/interrupt_handler.rb:84:in `isolate_from_interrupts'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/hook_runner.rb:24:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/cli.rb:203:in `run_all'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/cli.rb:28:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/bin/overcommit:7:in `<top (required)>'
	from /usr/local/bin/overcommit:23:in `load'
	from /usr/local/bin/overcommit:23:in `<main>'
```

Should I open a new issue for this?

**Comment by sds** [comment]
That particular error message can only happen if Overcommit can't find the hook plugin file. I'll add a TODO to make this more obvious as already mentioned, but in the end your configuration must still be wrong.

Are you _sure_ your directory is called `.git_hooks` (with an underscore?). The default is `.git-hooks`. What is the output of `ls -al .git*` in your repo?

Double-check the directory name of your plugin directory, triple-check that it has a directory within it called `pre_commit`, and quadruple-check that that directory has a file inside named `php_cs.rb` to match Ruby file naming conventions, as documented here: https://github.com/brigade/overcommit#repo-specific-hooks.

I'll try to better call out how important the case sensitivity is for the file name in the documentation.

**Comment by gms8994** [comment]
Okay; the issue was that the file should have been named `php_cs.rb`; once that was updated, the following message appears:

```
/Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/hook_loader/plugin_hook_loader.rb:72:in `check_for_modified_plugins': Overcommit::Exceptions::InvalidHookSignature (Overcommit::Exceptions::InvalidHookSignature)
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/hook_loader/plugin_hook_loader.rb:8:in `load_hooks'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/hook_runner.rb:146:in `load_hooks'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/hook_runner.rb:28:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/interrupt_handler.rb:84:in `isolate_from_interrupts'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/hook_runner.rb:24:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/cli.rb:203:in `run_all'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/lib/overcommit/cli.rb:28:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/overcommit-0.30.0/bin/overcommit:7:in `<top (required)>'
	from /usr/local/bin/overcommit:23:in `load'
	from /usr/local/bin/overcommit:23:in `<main>'
```

Solved by running `overcommit --sign pre-commit`. Another, new issue, sadly. Apologies if all of this should have been obvious. Using the config above for files to `includes` (ignoring the typo, which I've fixed), `applicable_files` doesn't only list `php` files, as I think I've defined. Is there something wrong with that portion of my config, that you can see?

Thank you, again, for your quick replies. You've been a tremendous help to me, and I'm extremely appreciative.

**Comment by sds** [comment]
If your `.overcommit.yml` looks like:

```yaml
PreCommit:
  ...
  PhpCs:
    enabled: true
    ...
    include:
      - '**/*.php'
  ...
```

...then you should only see files ending in `.php` in your list of applicable files. If that's not the case, I encourage you to double-check for typos again, as this really should be working as-is (provided you don't have any other strange configuration in your `.overcommit.yml`. 

For sake of simplicity, you could try reducing your `.overcommit.yml` to only have configuration for the `PhpCs` hook to help you debug.

**Comment by gms8994** [comment]
Perfect. The problem was that I had `includes`, and not `include`. Perhaps when parsing out the config file, this could be added to the check (not sure how, but checking for misspellings, maybe?).

Again, thanks for your help, and I'm very grateful for the effort you've put in to this project.

**Comment by sds** [comment]
I'm glad that helped figure out the problem, @gms8994.

You've pointed out some areas that we definitely need to improve on (and haven't been the first). Overcommit should fail fast and loudly rather than silently when obviously-wrong configuration is present.

In the case of `include` however, while I like the idea of checking for spelling errors, you never know if someone will write a custom hook that wants to name one of its custom options `includes`. Perhaps there's an argument here for Overcommit to forbid some common typo names of options, but it's typically easier to just let it be.

**Comment by lencioni** [comment]
Not sure if it's worth the squeeze here, but we could require hooks that define custom options to statically specify a list of possible options and that could be taken into account when verifying configuration.

**Comment by gms8994** [comment]
One last question; shouldn't `applicable_files` (for a pre-commit hook) only contain files that have been staged via `git add`? If so, then my script above is getting a much longer list of files than are staged. If not, then I think I'm still doing something wrong.

**Comment by sds** [comment]
@lencioni yeah, this idea has come up in a couple of projects now. There are a lot of advantages (more self-documenting code, for example). Something I'd like to explore for sure.

@gms8994 your understanding is correct: `applicable_files` should only include staged files, meaning files in your index. What does `git diff --cached` show you? The files returned by `applicable_files` for your hook should be a subset of files in that list.

If you're doing an amendment, however, it will also include all the files that are in the commit you are amending (so it's as if you are creating the commit for the first time).

**Comment by gms8994** [comment]
`git diff --cached` shows a single file; `puts applicable_files` contains the vast majority of the source files to my application.

**Comment by sds** [comment]
How are you testing your hook? Are you executing `git commit`, or are you executing `git commit --amend`? The latter will result in significantly more files.

**Comment by gms8994** [comment]
Once again, I figured out my issue. Running with `-r` doesn't actually use the list of files that have been changed. Running with `git commit`, does. Feeling pretty dumb about all of this :)

**Comment by daanemanz** [comment]
I have a similar issue where I have created a new hook in a ruby gem, and the plugin does not seem to be loaded at all. Is there a way to load plugins via gems that have been installed through bundler?

**Comment by sds** [comment]
Hey @daanemanz, if you specify the `gemfile` option in your `.overcommit.yml`, and specify the `required_library` option for your hook, it will get loaded from the Bundler context you're running within (unless you're invoking the pre-commit hooks via `overcommit --run`, in which case you need to execute `bundle exec overcommit --run`).

See the documentation on the [`gemfile` option](https://github.com/brigade/overcommit/tree/v0.31.0#gemfile) to better understand what's going on.

**Comment by jawshooah** [comment]
@daanemanz Currently no, but that's an interesting idea. Mind creating a separate issue?

**Comment by sds** [comment]
Sorry, @jawshooah is right. I misread the question as simply trying to load code from a Ruby gem.

**Comment by jawshooah** [comment]
@sds I believe Overcommit will still choke if it can't find a corresponding hook in the configured plugin directory (`.git-hooks` by default, I believe). What @daanemanz seems to be asking for is the ability to define a custom hook in a gem, add it to the Gemfile, and configure it in `.overcommit.yml` without having to add a shim to `.git-hooks/pre_commit` or other.

**Comment by jawshooah** [comment]
Sorry about that, I prematurely deleted my comment when I saw yours :stuck_out_tongue_closed_eyes:

**Comment by daanemanz** [comment]
@jawshooah - that's exactly what I was looking for. I'll create a separate issue and look into ways to make the magic happen.
