### ISSUE TITLE
Pre-commit hook proposal: maximum JPEG quality

### ISSUE THREAD

**Issue by lencioni** [sds/overcommit#349]
JPEGs saved at too high quality are unnecessarily large. It is often undesirable to commit large files to a repo and to ship images that are unnecessarily large. It would be nice if there was a pre-commit hook that would check the image quality of JPEGs (and other image types if possible) and prevents them from being committed if they are above a maximum image quality threshold.

The JPEG quality level can be found via imagemagick's `identify` command (`identify -format '%Q' image.jpg`) but it would be really nice to find a way to do this without the imagemagick dependency so that it will work for as many people as possible. Maybe there is a gem that can do this? If not, it looks like [imagemagick determines compression quality from the quantization tables](http://superuser.com/a/91083/36209) ([code](https://github.com/ImageMagick/ImageMagick/blob/05d2ff7ebf21f659f5b11e45afb294e152f4330c/coders/jpeg.c#L818)) so that might be a good approach to borrow.

**Comment by sds** [comment]
Closing due to age. Happy to accept a pull request if this is desired!
