### ISSUE TITLE
rails_best_practices filtering out executable errors

### ISSUE THREAD

**Issue by nolanpro** [sds/overcommit#356]
https://github.com/brigade/overcommit/commit/ef36c65355ece895eb430c2d3c1324db2fa1f7a8#diff-840451328e54e76c09c65ca3803b409dR24

`filter_output(stdout)` filters using ERROR_REGEXP, even though that regex is sent to `extract_messages` also. This filters out errors like `bundler: command not found: rails_best_practicess` (notice the typo at the end, it's from the yml `command: ['bundle', 'exec', 'rails_best_practicess']`. Bundler throws the error but overcommit never picks it up, giving a false 'pass' for the hook. Thanks!!

**Comment by sds** [comment]
Hey @kovpack, do you have any thoughts on this? It would be useful for the `RailsBestPractices` hook to catch the situation @nolanpro describes. 

Since I don't use the hook, I'm not familiar with the kind of output it typically returns, and whether `filter_output` is necessary in this context.

**Comment by sds** [comment]
Closing due to age. Happy to accept a pull request if this is desired.
