### ISSUE TITLE
Overcommit always uses default rubocop configuration

### ISSUE THREAD

**Issue by l8on** [sds/overcommit#42]
I have a custom `.rubocop.yml` file in my repo. It is used correctly when running
rubocop directly, but when overcommit performs its rubocop pre-commit hook it seems to always use the default configuration. 

This was working with overcommit 0.5.0, but stopped after upgrading to version 0.7.0 and rubocop 0.19.1.
Does my rubocop.yml need to be in a specific place? Do I need to re=run the install script?

**Comment by franzejr** [comment]
I have one question related to that. I have a `.rubocop.yml` file in my repository and I am also using overcommit. I feel like overcommit is not using my rubocop configuration file.I'm using the 0.31.0 version.

**Comment by sds** [comment]
Make sure your `.rubocop.yml` file is committed/staged, otherwise Overcommit will temporarily erase it during pre-commit hooks (as mentioned above).
