### ISSUE TITLE
Pull request for Lolcommit

### ISSUE THREAD

**Issue by quintrino** [sds/overcommit#500]
Hi, I'm currently building a rough implementation to work with the lolcommits gem. 

Wanted to check if I polish it up and submit a pull request is this a feature you're interested in?

Thought I'd check in before creating it (especially considering it's slightly silly nature. 😛  )

**Comment by Br3nda** [comment]
I would like this feature -- i've been cludging it into my git hooks for a while.
Send me a link and i can test it.

**Comment by sds** [comment]
Happy to merge a pull request. Closing this as it hasn't been actioned.
