### ISSUE TITLE
Can Prepush hooks not run when deleting branches from remotes?

### ISSUE THREAD

**Issue by Br3nda** [sds/overcommit#501]
this removes the branch from the remote:

`git push upstream :test-write-access`

overcommit jumps in and wants the hooks to pass before it can be deleted. I don't think this makes much sense to require this before deletion.

Could overcommit detect this and not run?

**Comment by sds** [comment]
Hey @Br3nda, thanks for pointing out this issue.

The problem with disabling Overcommit pre-push hooks when deleting remote branches is that there are legitimate times where you would want to run a pre-push check in that situation.

Ideally pre-push hooks should be written to explicitly ignore the branch deletion case. However, given the overwhelming likelihood that most pre-push hooks don't care about branch deletion, perhaps we can add a generic configuration option `ignore_branch_deletions` for pre-push hooks, which defaults to `true`.

Would love a pull request!

**Comment by sds** [comment]
Implemented in #690.
