### ISSUE TITLE
Request: improve information around "Unable to restore working tree after pre-commit hooks run"

### ISSUE THREAD

**Issue by brandondrew** [sds/overcommit#504]
When the user is notified that Overcommit is
> Unable to restore working tree after pre-commit hooks run
it would be helpful to explain that their working tree has been stashed.  

There are presumably very good reasons for Overcommit to stash the working tree.  But I cannot think of any reason not to inform the user of this, or to assume they already are aware of it.

I expect this would help resolve problems like #135 .

**Comment by sds** [comment]
Added a note in a15edd2df9f3c3626112a84f92c5cf8a6b39d3d3.
