### ISSUE TITLE
Show actual differences between current hooks/configuration and the last known good signature

### ISSUE THREAD

**Issue by mvz** [sds/overcommit#561]
When a new overcommit version is installed, it produces the following output:

```
Hooks updated to Overcommit version 0.43.0
Signature of configuration file has changed!
Run `overcommit --sign` once you've verified the configuration changes.
For more information, see https://github.com/brigade/overcommit#security
```

However, the configuration file itself hasn't changed, and the changes to the hook scripts are not easily shown since they're not under version control. How is the user supposed to verify in this case?

**Comment by sds** [comment]
Hey @mvz, we don't have a good answer for this right now. At the end of the day, we want to warn the user that something has changed. It's their prerogative to either simply trust the new version or explicitly research what has changed themselves.

I agree it would be great to provide better information here. Would love a pull request that perhaps showed a diff of the two configurations, along with any diff changes for the hooks themselves!
