### ISSUE TITLE
required_executable  can not find my files

### ISSUE THREAD

**Issue by wwhgtt** [sds/overcommit#564]
here is my question 
![image](https://user-images.githubusercontent.com/8405520/37503765-30496c1a-2915-11e8-8c50-d14ec95357c5.png)
![image](https://user-images.githubusercontent.com/8405520/37503773-3969d1c2-2915-11e8-96dd-cce8a1addf57.png)
![image](https://user-images.githubusercontent.com/8405520/37503781-44097560-2915-11e8-9610-4af9d2a00d79.png)

**Comment by wwhgtt** [comment]
i am using windows

**Comment by sds** [comment]
Hey @wwhgtt, in general we can't help you unless you can link us to the repository in question so we can try to reproduce locally. The fact that you are on Windows makes this more difficult, as I don't have access to a Windows machine. 

If you can rule out all of the potential issues the error message, then I'm not sure what could be going wrong here, and would appreciate you digging into this on your side.

**Comment by wwhgtt** [comment]
https://github.com/wwhgtt/FE_basic_structure.git   here is my project
