### ISSUE TITLE
Overcommmit is confused when two versions of overcommit  is installed

### ISSUE THREAD

**Issue by electron0zero** [sds/overcommit#577]
When you have two versions of overcommit, it gets confused and issue #499 happens

**Steps to reproduce:**
Install `overcommit-0.44.0` && `overcommit-0.45.0`
Go to any repo. with overcommit hooks and try doing any operations which has hook on it.

**workaround**
keep only one version of overcomit

**what should happen**
Instead of #499, we show a helpful warning that you have two version of overcommit and uninstall one of them.

**Comment by HarlemSquirrel** [comment]
This is not great since I use overcommit with multiple projects and the versions are not always the same in my Gemfile.lock

**Comment by sds** [comment]
Closing due to age. If this is a still a problem, would appreciate a pull request fixing it!
