### ISSUE TITLE
Add support for requiring GPG signed commits

### ISSUE THREAD

**Issue by software-opal** [sds/overcommit#587]
First of all, this is awesome and we absolutely love it; it makes life so much easier for us.

As part of a migration we'd like to start requiring all the commits into our repo be GPG signed and it would be awesome if we could add that check into overcommit so that we don't accidentally forget to sign them.

Ideally we'd like support for running this check during the `post-commit`, `pre-push`, and `post-fetch` stages. Basically saying: did we sign this commit; did we sign all the commits we're pushing; and are all the commits we're fetching signed.

I'd appreciate your feedback before I start so it fits with your overall goals.

**Comment by sds** [comment]
Hey @leesdolphin, happy to merge a pull request!

One comment: you'll have to give some thought as to what kind of behavior you want to enforce about what kind of signatures you'll access for a particular author. As it stands, you can sign a commit with any GPG key—it doesn't matter if the email address of the key matches the author of the commit.

Furthermore, you'll have to think about how you deal with compromised keys.

I imagine rebase workflows (or cherry picking) will get quite difficult with this kind of enforcement.

However, if you're comfortable with those limitations, go for it!

**Comment by sds** [comment]
Closing due to age. Happy to accept a pull request with tests. Thanks!
