### ISSUE TITLE
Skip hooks on specific remote repos?

### ISSUE THREAD

**Issue by hadees** [sds/overcommit#588]
I'm having some trouble with `GitLfs`.  Heroku doesn't support it and the only way I can get the push to work is to do `SKIP=GitLfs git push staging develop:master`.  While that works fine it's kind of annoying given I have to do this every time.  I thought about just creating a deploy script but I'd rather have overcommit just ignore some hooks when pushing to a specific repo.

**Comment by hadees** [comment]
@sds the large files are used for seeding development and test databases.  They aren't needed on production.

**Comment by ronalddas** [comment]
Hi, any update on this? I need overcommit to ignore hooks for some git branches. Basically. I want to run tests before pushing to the master branch using the pre-push hook. But I don't want the same to happen for the dev branch

**Comment by hadees** [comment]
@ronalddas nope, i ended up just removing the large files from the repo.

**Comment by sds** [comment]
Implemented in #683.
