### ISSUE TITLE
When Overcommit gem is installed in a Nix environment, updating hooks fails

### ISSUE THREAD

**Issue by ento** [sds/overcommit#607]
How to repro: https://gist.github.com/ento/a77fb97f581bdea4ed27c845107308bf

Why this happens:

- Nix makes all package files read-only upon installation. See the last bullet point of https://nixos.org/nix/manual/#ssec-derivation
- Overcommit installs hooks by copying files included in its gem
- Since the copied files are read-only, trying to overwrite them fails when installing hooks again, which can also happen when updating hooks

Potential fix: set the writable flag after copying hook files.

If that is an acceptable fix, I can take a stab at a PR.

**Comment by sds** [comment]
Hey @ento, thanks for the report! Appreciate the detail you've included.

Your proposed solution seems reasonable to me. Would love a PR!

**Comment by Gerschtli** [comment]
Hey, I would love to fix this, can you give me a rough pointer where I can start to look? I've never done anything in ruby before

**Comment by ento** [comment]
(Sorry I haven't been able to get to a PR. @Gerschtli If you can move things forward here, I'd be grateful!) My progress so far is:

- Found where hook files are copied:
  - [the master hook is copied first](https://github.com/brigade/overcommit/blob/5692b4e9d58c5e587928f528f6df66df903a2a6f/lib/overcommit/installer.rb#L103)
  - [it is then copied for each hook type](https://github.com/brigade/overcommit/blob/5692b4e9d58c5e587928f528f6df66df903a2a6f/lib/overcommit/installer.rb#L120)
- Wondered how to write tests
  - Initially, as a feature that interacts with an external system (the filesystem), `spec/integration/installing_overcommit_spec.rb` seemed like where it should be tested
  - However, the location of the master hook file is hardcoded as [`lib/overcommit/../..`](https://github.com/brigade/overcommit/blob/ec8795c976c2ee11d8ccb6890f3118c954252eff/lib/overcommit/constants.rb#L5)[`/template-dir/hooks/overcommit-hook`](https://github.com/brigade/overcommit/blob/5692b4e9d58c5e587928f528f6df66df903a2a6f/lib/overcommit/installer.rb#L8-L9). I wouldn't want to change the permission of this file, which will be the checkout of this repo during development.
  -  `spec/overcommit/installer_spec.rb` runs tests against the filesystem => it seems easier to test it there instead: create a temporary file and use [stub_const](https://github.com/brigade/overcommit/blob/5692b4e9d58c5e587928f528f6df66df903a2a6f/spec/overcommit/hook/pre_commit/w3c_css_spec.rb#L14) to override the location of the master hook file

@sds ^Corrections welcome!
