### ISSUE TITLE
custom starter.yml

### ISSUE THREAD

**Issue by quintrino** [sds/overcommit#613]
Hi, 

I just wanted to check if there was a way to set a custom starter.yml that gets installed with overcommit --install
I've set the overcommit default config as my default git template, but I'd like to have running overcommit --install always include
```
PreCommit:
  All: 
    quiet: true
```
Apologies if I've missed a config option somewhere. 

EDIT:
Reflecting on this a bit further I realised that a partial solution since I have 
`export GIT_TEMPLATE_DIR="$(overcommit --template-dir)"` in my shell rc file.
is I could create an alias that copies my custom .overcommit.yml into the root directory of the git project I'm in instead of running overcommit --install. 

However then I still have to run this new alias every time I start a new project so it might actually be better to have the option to set a custom default config instead, that way, even if I don't have a .overcommit.yml file in my git repo it will still run precommits quietly. 
I assume manually editing the default config file inside the gem would be a bad idea / get overwritten the next time the gem updates? 

Curious on everyone's thoughts.

**Comment by sds** [comment]
There is not currently a way to do this. Open to a pull request adding support!
