### ISSUE TITLE
Add support for sass-lint pre-commit hook

### ISSUE THREAD

**Issue by iodic** [sds/overcommit#619]
As the scss-lint tool might not be able to check for all features in Sass going forward, are there any plans for supporting [sass-lint](https://github.com/sasstools/sass-lint) as a pre-commit hook?

Thanks!

**Comment by sds** [comment]
No plans—feel free to submit a PR!

**Comment by sds** [comment]
Closing due to age. Happy to merge a pull request adding support for sass-lint!
