### ISSUE TITLE
TrailingWhiteSpace failing even if no trailing whitespaces

### ISSUE THREAD

**Issue by risafj** [sds/overcommit#634]
Why is my PreCommit hook `TrailingWhitespace` failing even though there are no trailing whitespaces?
I was using overcommit with `RuboCop` and `TrailingWhitespace`, and it used to work just fine. My `.overcommit.yml` looked like this:

```ruby
PreCommit:
 RuboCop:
   enabled: true
   on_warn: fail # Treat all warnings as failures

 TrailingWhitespace:
   enabled: true
   exclude:
     - '**/db/structure.sql' # Ignore trailing whitespace in generated files
     - '/log/*'
```

I decided to add `RailsBestPractices` to the mix, and I don't know if it's because of that, but the trailing whitespace error started ever since. This is the error message:

```
Analyze with RailsBestPractices..................[RailsBestPractices] FAILED
Errors on modified lines:
/Users/me/projects/project_name/.overcommit.yml:26 - remove trailing whitespace

Check for trailing whitespace....................[TrailingWhitespace] FAILED
Errors on modified lines:
/Users/me/projects/project_name/.overcommit.yml:26:
```

When I run `rails_best_practices` by itself, there are no such errors. Besides, there is no trailing whitespace in that particular line. So I've no idea what the cause is.
I tried deleting `RailsBestPractices` from the config file, but still got the `[TrailingWhitespace] FAILED` error.

**Comment by risafj** [comment]
I went back to the previous commit and redid the configuration again. This time, all the hooks passed, but Rubocop didn't seem to run, since the line `Analyze with RuboCop` is missing. Are any of my hooks incompatible with another?

```
Running pre-commit hooks
Check for trailing whitespace....................[TrailingWhitespace] OK
Analyze with RailsBestPractices..................[RailsBestPractices] OK

✓ All pre-commit hooks passed
```

My `.overcommit.yml` file:
```ruby
PreCommit:
 RuboCop:
   enabled: true
   on_warn: fail # Treat all warnings as failures

 TrailingWhitespace:
   enabled: true
   exclude:
     - '**/db/structure.sql' # Ignore trailing whitespace in generated files
     - '/log/*'

 RailsBestPractices:
   enabled: true
```

**Comment by sds** [comment]
Hey @risafj,

It's hard to know what's going on from the information here. My best guess is that you haven't staged the changes to your `.overcommit.yml` when you run `git commit`. This causes those unstaged changes to be stashed, and so you might see differences in behavior between `git commit` and `overcommit --run`.
