### ISSUE TITLE
Stylelint do not handle problem_on_unmodified_line

### ISSUE THREAD

**Issue by leblangi** [sds/overcommit#638]
When i run **Stylelint** with a file who have many coding errors and I have a newly committed error, There is no differences between this two.

My understanding of _handle problem_on_unmodified_line_ is that it will warn by default the errors not in modified lines (and put then in yellow warn mode) and if I set the value to _ignore_, it will only show modified lines with errors.

This is currently not the case. It always show all errors.

**Comment by sds** [comment]
It would be helpful if you linked to an example repository or listed the commands you ran, the output, and what you expected the output to be. It's not clear what the issue is from your description. Thanks!

**Comment by marko-avlijas** [comment]
You probably mispelled stylelint (capitalization). I've had same problem with rubocop because I've misspelled `Rubocop` instead of `rubocop`
