### ISSUE TITLE
Rubocop doesn't respect problem_on_unmodified_line setting

### ISSUE THREAD

**Issue by marko-avlijas** [sds/overcommit#639]
It gives same output if I run it with `overcommit --run` or if I change just one or no .rb files and try to make a commit.
It's always `641 files inspected, 2277 offenses detected`. Eslint respects the settings and doesn't report anything on unmodified lines if I just make a commit, but it reports 1000s of errors if I run it  with `overcommit --run`.

So eslint is good,  rubocop is broken.

This is my `.overcommit.yml`:

    PreCommit:
      ALL:
        problem_on_unmodified_line: ignore
      Rubocop:
        enabled: true
        description: 'Analyze with RuboCop'
        required_executable: 'rubocop'
        flags: ['--force-exclusion', '--display-cop-names']
        install_command: 'gem install rubocop'
        include:
          - '**/*.gemspec'
          - '**/*.rake'
          - '**/*.rb'
          - '**/*.ru'
          - '**/Gemfile'
          - '**/Rakefile'

      EsLint:
        # on_warn: fail # this disables ignoring problems on unmodified lines
        enabled: true
        description: 'Analyze with ESLint'
        required_executable: 'npx'
        include:
          - app/javascript/**/*.js
        install_command: "echo 'According to documentation this was never supposed to be run'"
        command: ['npx', 'eslint']

      TrailingWhitespace:
        enabled: true
        exclude:
          - '**/db/structure.sql' # Ignore trailing whitespace in generated files

    #  BundleAudit:
    # enabled: true
    # on_fail: warn
    # flags: ['--update']

    PostMerge:
      BundleInstall:
        enabled: true

I see same issue with different linter here:
https://github.com/sds/overcommit/issues/638

Please fix your problem_on_modified_line setting so all linters actually respect it.

**Comment by marko-avlijas** [comment]
Also attaching .rubocop.yml (renamed because github has a list of files it supports based on extension)
[rubocop.yml.txt](https://github.com/sds/overcommit/files/3176894/rubocop.yml.txt)

**Comment by marko-avlijas** [comment]
I've figured it out. My hook is misspelled `Rubocop` instead of `Rubocop` and I got no warning.

Probably fix is to change line 85 in plugin_hook_loader.rb

        def run
          result = @context.execute_hook(command, args: applicable_files)

Ad hoc hooks also need to get applicable_files.

**Comment by sds** [comment]
This is intended behavior. When using ad hoc hooks, you are running the Git hook as it would be run normally, i.e. not within the context of an Overcommit run.

In the case of a pre-commit hook, you can see that it takes no parameters when run:
https://git-scm.com/docs/githooks/2.19.0#_pre_commit
>It takes no parameters, and is invoked before obtaining the proposed commit log message and making a commit. 

When creating ad hoc hooks, **you** are responsible for passing the appropriate files.

**Comment by marko-avlijas** [comment]
> When creating ad hoc hooks, **you** are responsible for passing the appropriate files.
Well if I have enabled an option for all hooks, using `ALL:` then I expect it to work for all hooks.
