### ISSUE TITLE
Feature request: unmodified output for ad hoc hooks

### ISSUE THREAD

**Issue by marko-avlijas** [sds/overcommit#640]
Output of linters, especially EsLint is much more prettier than output of overcommit - either everything in red or everything in white if no color is specified. It would be amazing if we could get unchanged output of linter, that would make it easier to spot errors.

IMO overcommit doesn't need to analyze lines at all, just fail if rubocop / eslint returns an error.
Leave it to developer to analyze the errors.

**Comment by sds** [comment]
Open to this behavior for ad hoc hooks, as I think there is greater precedent in that situation for Overcommit to not touch the hook output.

Disagree with this behavior for built-in hooks. When building a hook in Overcommit, the expectation is that Overcommit is modifying the output based on what it thinks is best, as it is a holistic framework for hooks.

With that said, would be open to a pull request that enables this for ad hoc hooks. I'm changing the title of this request accordingly.

**Comment by marko-avlijas** [comment]
> Open to this behavior for ad hoc hooks, as I think there is greater precedent in that situation for Overcommit to not touch the hook output.

My expectations are different. I expect it to parse output only if it can do something useful with it, like run `rubocop --safe-auto-correct` on failed files. From my experience using overcommit on less than 3 commits, it just needs to fail if linter reports an error, nothing more. Making output less pretty is not a  needed feature.
