### ISSUE TITLE
Where do these YamlSyntax errors come from?

### ISSUE THREAD

**Issue by veganstraightedge** [sds/overcommit#642]
My `.overcommit .yml`

```yaml
PreCommit:
  YamlSyntax:
    enabled: true
```

# Errors in output 

When I run `overcommit -r`

```
Running pre-commit hooks
sh: -c: line 0: unexpected EOF while looking for matching `"'
sh: -c: line 1: syntax error: unexpected end of file
Check YAML syntax........................................[YamlSyntax] OK

✓ All pre-commit hooks passed
```

This is for https://github.com/crimethinc/website/

Thanks! I really appreciate y'all making and maintaining Overcommit! 🎉

**Comment by sds** [comment]
Thanks for the report, @veganstraightedge. 

This actually had nothing to do with the `YamlSyntax` hook. Fixed in 7e8e6f21ab10a579beb9f9c49478040ef10d8e22.

**Comment by veganstraightedge** [comment]
Great! Thanks @sds. What's the process/timeline for that change landing in the homebrew recipe?

**Comment by sds** [comment]
This project doesn't maintain a Homebrew formula, so I would ask the maintainer.

**Comment by veganstraightedge** [comment]
Thanks

**Comment by veganstraightedge** [comment]
Sorry. I was moving too fast and not thinking through what I actually meant.

What I should've asked was, what's the process/timeline to release a new patch version of the `overcommit` gem?

**Comment by sds** [comment]
We don't have any clear schedules published at this time.

[0.48.1](https://rubygems.org/gems/overcommit/versions/0.48.1) has been released.

**Comment by veganstraightedge** [comment]
Righteous! Thanks again.

/end
