### ISSUE TITLE
CargoTest Broken In Non-Rust Projects

### ISSUE THREAD

**Issue by jfelchner** [sds/overcommit#644]
I'd love to see some sort of check in the `CargoTest` pre-push hook that checked to see if there was a `Cargo.toml` or any `*.rs` files in the project before it tried to run it.

**Comment by sds** [comment]
Hey @jfelchner, can you help me understand why the `CargoTest` pre-push hook would be enabled in the first place for a new project that didn't have any Rust files?

**Comment by jfelchner** [comment]
@sds the way I use overcommit, I have the same config utilized across all of my projects.  I'm a consultant so I have dozens active at a given time.  When I update my overcommit config, I copy it to all of my projects automatically via some commands and scripts.  I could theoretically have a "rust only" version of my overcommit config, but up until this point all of my configuration has been of the "it doesn't run it if it doesn't need to" variety.  So I could enable, for example, rubocop's check on every project, and if it wasn't a ruby project with ruby files, it wouldn't run it.  I'd just like to see all the hooks behave in the same manner.

Hope this helps.

**Comment by sds** [comment]
Thanks for clarifying. Would welcome a pull request!
