### ISSUE TITLE
Feature request: SpellCheck improvement?

### ISSUE THREAD

**Issue by diegojromerolopez** [sds/overcommit#646]
Hello developers and maintainers of overcommit.

I have developed an [advanced SpellCheck tool](https://github.com/diegojromerolopez/alfonsox) that allows to set which dictionaries you want to use. Currently it supports LibreOffice dictionaries (included in the gem), RubyMine ones or a custom hunspell dictionary given a path. Thus, you can use several dictionaries of several different or same languages.

Would you be interested in having this feature in overcommit? Do you miss any feature to be included in overcommit? And, what name do you think would be the best for this pre-commit hook? Note SpellCheck is taken.

If you are interested in this feature, I will do the PR.

Cheers.

**Comment by diegojromerolopez** [comment]
This questions were a bit cryptic. My problem is based on having a team that writes code in English but they are not English speakers and this tool can help them.

if you want to see my solution for this problem, see te following PR: https://github.com/sds/overcommit/pull/654

**Comment by sds** [comment]
Merged in #654.

**Comment by diegojromerolopez** [comment]
Thank you!
