### ISSUE TITLE
Shell Command with Pipes?

### ISSUE THREAD

**Issue by diegojromerolopez** [sds/overcommit#647]
Hello all.

I'm trying to develop a pre-commit hook that check Ruby syntax with the following shell command:

```sh
find . -name "*.rb"  -exec ruby -c {} \; | grep -q 'Syntax OK'
```

Trying to run this command with execute helper raises an exception: **Cannot pipe commands with the `execute` helper**.

Can anyone give some orientation about what would be the best solution? Creating a sh file and calling it from the **execute** helper method or running the command with **system**?

Thank you.

**Comment by sds** [comment]
Hey @diegojromerolopez,

Your command as written would not work because `|` would be passed as a literal argument to the `find` command. If you want it to be treated as a shell pipe character, you need to write your command as:

```
bash - c 'find . -name "*.rb"  -exec ruby -c {} \; | grep -q "Syntax OK"'
```
i.e. the Ruby array:
```
['bash', '-c', 'find . -name "*.rb"  -exec ruby -c {} \; | grep -q "Syntax OK"']
```

Hope that helps.

**Comment by diegojromerolopez** [comment]
Thank you very much for your guidance @sds.

I just completed a PR with the RubySyntax pre-commit: https://github.com/sds/overcommit/pull/648
