### ISSUE TITLE
undefined method `match?' for "BowerInstall":String

### ISSUE THREAD

**Issue by leek** [sds/overcommit#663]
Not sure what I'm doing wrong?

```
undefined method `match?' for "BowerInstall":String
Did you mean?  match
/Users/chrjones3/.gem/gems/overcommit-0.49.1/lib/overcommit/configuration_validator.rb:105:in `block (2 levels) in check_hook_name_format'
/Users/chrjones3/.gem/gems/overcommit-0.49.1/lib/overcommit/configuration_validator.rb:102:in `each_key'
/Users/chrjones3/.gem/gems/overcommit-0.49.1/lib/overcommit/configuration_validator.rb:102:in `block in check_hook_name_format'
/Users/chrjones3/.gem/gems/overcommit-0.49.1/lib/overcommit/configuration_validator.rb:101:in `each'
/Users/chrjones3/.gem/gems/overcommit-0.49.1/lib/overcommit/configuration_validator.rb:101:in `check_hook_name_format'
/Users/chrjones3/.gem/gems/overcommit-0.49.1/lib/overcommit/configuration_validator.rb:21:in `validate'
/Users/chrjones3/.gem/gems/overcommit-0.49.1/lib/overcommit/configuration.rb:20:in `initialize'
/Users/chrjones3/.gem/gems/overcommit-0.49.1/lib/overcommit/configuration_loader.rb:34:in `new'
/Users/chrjones3/.gem/gems/overcommit-0.49.1/lib/overcommit/configuration_loader.rb:34:in `load_from_file'
/Users/chrjones3/.gem/gems/overcommit-0.49.1/lib/overcommit/configuration_loader.rb:15:in `default_configuration'
/Users/chrjones3/.gem/gems/overcommit-0.49.1/lib/overcommit/configuration_loader.rb:59:in `load_repo_config'
.git/hooks/pre-commit:72:in `<main>'
Report this bug at https://github.com/sds/overcommit/issues
```

**Comment by sds** [comment]
Which version of Ruby are you running? `match?` is a standard method defined on `String`.

- https://ruby-doc.org/core-2.4.6/String.html#method-i-match-3F
- https://ruby-doc.org/core-2.5.5/String.html#method-i-match-3F
- https://ruby-doc.org/core-2.6.3/String.html#method-i-match-3F

If your runtime doesn't define `match?`, there's something odd with your environment.

**Comment by leek** [comment]
`▶ ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]`

**Comment by sds** [comment]
What does:
```
ruby -e 'puts "test".match?(/\A[A-Za-z0-9]+\z/)'
```
Display for you?

**Comment by sds** [comment]
To ensure you're loading all the gems that are `require`d in your project, make sure you run the above in whatever project you're seeing this issue in with `bundle exec`, so:
```
bundle exec ruby -e 'puts "test".match?(/\A[A-Za-z0-9]+\z/)'
```

**Comment by perseusdo** [comment]
@sds I got the same issue while running `overcommit --install`. 
I run your command and it printed `true`.
I am using ruby 2.6.3 installed via RVM.

**Comment by sds** [comment]
I don't know what else to offer here—if running the above code within `bundle exec` works in your environment for that command but not Overcommit, there's something out of the ordinary with your Ruby installation.

I'm going to close this as there's nothing further to provide, but if anyone figures this out would appreciate you posting what the issue was so others can fix. My best guess is that you may have Ruby 2.6 installed on your system, but when you invoke Overcommit it is running a system version of Ruby which is running Ruby < 2.4. I don't know how this could happen (installing via Homebrew?) but given it's a local issue and not an issue with Overcommit itself, I'm closing this out.

**Comment by leek** [comment]
@sds Running that command in my project outputs this:

```
▶ bundle exec ruby -e 'puts "test".match?(/\A[A-Za-z0-9]+\z/)'
Could not locate Gemfile or .bundle/ directory
```

I definitely believe that overcommit is not running the Ruby I have installed with rbenv but I'm not sure how to make it, either. The default Ruby on my Mojave system is 2.3.7.

**Comment by perseusdo** [comment]
@leek Yeah, I am running ZSH, seems like it's working now, I re-installed the RVM and Ruby as well. Thanks for the help @sds @leek
