### ISSUE TITLE
Do not run stash operations when not necessary

### ISSUE THREAD

**Issue by deanius** [sds/overcommit#669]
Issues #135 and #504 indicate that the stashing process, while convenient for a certain use case, introduces issues and risk of loss of files, under edge cases.

Editor flicker (VSCode on Mac, at least), the possibility that an abort (via `^C`) leaves the working tree worse than before - these are issues that users need not be exposed to if they have a workflow where the hooks can and should be run on the entire working tree, because they have no unstaged changes while committing.

We discussed the desirability of this on #135 and I'm opening this issue to attach a PR to. Will need some help! But I think there will be a benefit to users who enjoy Overcommit, but who don't regularly make commits with only some of the changes staged..

I can add that my workflow, involves using stashes for the sake of applying `console.log` and other non-commit-worthy diffs, and manual reversion. I don't try to write the commit message and run hooks and commit until my tools very clearly show me what I'm committing and not. So I've never been in need of stashing. But perhaps by excluding use cases like mine from stashing, Overcommit can provide the best of both worlds.

**Comment by sds** [comment]
Hey @deanius, thanks for putting together a proposal.

If there isn't a clear way to determine whether a stash had occurred, then perhaps we should simply structure the code to check if a given method was called.

For example, extract: https://github.com/sds/overcommit/blob/5a6ca8990b2859b75be14a2e5606daa194a4c218/lib/overcommit/hook_context/pre_commit.rb#L53-L68 into a helper method `stash_changes`, and in our tests validate that the helper method was never called in the case we are trying to validate.

```ruby
    context 'when all changes have been staged' do
      around do |example|
        repo do
          echo('Hello World', 'tracked-file')
          echo('Hello Other World', 'other-tracked-file')
          `git add tracked-file other-tracked-file`
          example.run
        end
      end

      it 'does not stash changes' do
        expect(context).to_not receive(:stash_changes)
        subject
      end
```

...simliarly for `cleanup_environment` tests:

```ruby
      it 'does not restore the stash' do
        expect(context).to_not receive(:restore_stash_changes)
        subject
      end
    end
```

Does that seem reasonable?

**Comment by deanius** [comment]
I'm definitely in agreement, but not expert with Ruby mocking and event the first assertion here doesn't pass..

```rb
      it 'does not stash changes' do
        expect(context).to receive(:setup_environment)
        expect(context).to receive(:stash_changes)
      end
```

I hope this doesn't mean I'm at the end of my line trying to help, but I'm not sure I can.
