### ISSUE TITLE
Can't get Fasterer to fail when running `bundle exec overcommit --run`

### ISSUE THREAD

**Issue by Diego-Zulu** [sds/overcommit#691]
Hey there, I'm in need of some help getting the `Fasterer` hook to fail when running `bundle exec overcommit --run`

These are the steps I took so far:

1. `rails new overcommit-test` (with rails 6.0.0) and cd into the folder
2. `bundle add overcommit`
3. `bundle exec overcommit --install`
4. `bundle add fasterer`
5. Remove all comments from `.overcommit.yml`, and then add these lines:
```
gemfile: Gemfile

PreCommit:
  ALL:
    on_warn: fail

  Fasterer:
    enabled: true
```
6. `bundle exec overcommit --sign`
7. `git add .` and commit
8. Run `bundle exec fasterer`, no offenses are detected
9. Break some fasterer rule. I decided to break the Hash#fetch with second argument rule, so I added to my `application_controller.rb` the lines
```
a = {}
a.fetch('a', 'b')
```
10. Run `bundle exec fasterer`, and verify it's detecting only 1 offense, and said offense is from the lines I just added
11. `bundle exec overcommit --run` runs the fasterer hook. It should fail but passes
12. Then I try `git add .` and commiting. In this case overcommit runs the fasterer hook and fails correctly!
13. I try `bundle exec overcommit --run` one more time, with same result. Hook runs but does not fail.

Anybody knows what could be happening?

**Comment by sds** [comment]
Hey @Diego-Zulu,

This is an issue with `fasterer` not reporting a non-zero exit status when a file it attempts to scan isn't parseable. 

When you run `overcommit --run`, you are effectively running the following with the `Fasterer` hook:

```bash
cd overcommit-test
echo app/channels/application_cable/channel.rb,app/channels/application_cable/connection.rb,app/controllers/application_controller.rb,app/helpers/application_helper.rb,app/jobs/application_job.rb,app/mailers/application_mailer.rb,app/models/application_record.rb,config/application.rb,config/boot.rb,config/environment.rb,config/environments/development.rb,config/environments/production.rb,config/environments/test.rb,config/initializers/application_controller_renderer.rb,config/initializers/assets.rb,config/initializers/backtrace_silencers.rb,config/initializers/content_security_policy.rb,config/initializers/cookies_serializer.rb,config/initializers/filter_parameter_logging.rb,config/initializers/inflections.rb,config/initializers/mime_types.rb,config/initializers/wrap_parameters.rb,config/puma.rb,config/routes.rb,config/spring.rb,db/seeds.rb,test/application_system_test_case.rb,test/channels/application_cable/connection_test.rb,test/test_helper.rb | tr ',' "\n" | xargs bundle exec fasterer
```

If you run this in your directory, you'll see output like:
```
1 file inspected, 0 offenses detected
```

If you run just the following:
```bash
echo app/controllers/application_controller.rb | xargs bundle exec fasterer
```
...you'll get:
```
app/controllers/application_controller.rb:3 Hash#fetch with second argument is slower than Hash#fetch with block.

1 file inspected, 1 offense detected
```

This seems like a bug with `fasterer`. Suggest you open an issue with that project. Thanks!

**Comment by Diego-Zulu** [comment]
Hey, just as a follow up: You are right sds, turns out you can't even supply a list of files to run fasterer on. The only thing you can supply is a name of a folder to inspect into. I [created an issue](https://github.com/DamirSvrtan/fasterer/issues/75) to see if we could have this functionality added  to fasterer so we can make this hook work.
