### ISSUE TITLE
Add pre-commit hook for Puppetlabs PDK - need help with negative rspec tests

### ISSUE THREAD

**Issue by NeatNerdPrime** [sds/overcommit#694]
Greetings Overcommit team,

I've created an additional pre-commit hook that runs puppetlabs 'pdk validate' and it seems to work quite well. Reason for doing this is because:

* Puppetlabs has bundled the toolset of their own and it's great!
* It basically replaces the separate toolings like puppet-lint, yamllint, yamlsyntax, rubocop... 

However i am a bit struggling with the rspec tests, can't get negative testing right. Would you be so kind as to nudge me in the right direction to do this?

the spec test in question can be found [here](https://github.com/NeatNerdPrime/overcommit/blob/feature/introducing_puppetlabs_pdk/spec/overcommit/hook/pre_commit/puppet_pdk_spec.rb)

Once i have this right, i can squash and make a PR.

Thank you for your feedback.

**Comment by NeatNerdPrime** [comment]
@sds

**Comment by sds** [comment]
I'm not sure I understand your question, @NeatNerdPrime. The file you link to has no negative tests.

There are many examples of negative tests that have already been written. Here is one for RuboCop: https://github.com/sds/overcommit/blob/dd9ba2adcc5988ffd27e922486773c304bf2cc08/spec/overcommit/hook/pre_commit/rubo_cop_spec.rb#L37-L53.

Again, not sure I'm understanding what you're asking. I hope this helps.

**Comment by NeatNerdPrime** [comment]
Yeak kinda helps, what i don't understand is: Is the "file1.rb" which  is mentioned here some file added to the test suite that exists explicitly for raising this warning?  I'll try to figure it out and expect a PR in the coming days. Apologies for my late reply.

**Comment by sds** [comment]
Apologies for not responding. `file1.rb` is just fake output—it can be anything. In this case we're mocking the output.

Closing this ticket due to age, but feel to submit a pull request if you'd like to see this implemented!
