### ISSUE TITLE
Allow Hooks To Work With Multiple Hook Types

### ISSUE THREAD

**Issue by jfelchner** [sds/overcommit#697]
**Motivation:**

There are a lot of people on a lot of teams who balk at having precommit hooks slow them down on every commit.  As a compromise, they would like the checks to happen on push rather than on commit.  This is reasonable to me as all I care about is that the end result of the code is correct, especially if they're squashing their commit prior to merge.

The downside is, as the code currently stands, the hooks only know how to hook into one type (as far as I can tell) so, for example, if I wanted to run `rubocop` `PrePush` rather than `PreCommit` then I'd need to add a whole new hook.

**Potential Goals:**

What I'd like is the ability to have the hook files understand how they execute in various contexts rather than having completely separate hooks.  For example:

* Run against the entire project
* Run against specific files (for example files changed between the current commit and the base branch)
* Run against a diff

When a new hook is added, it's required that it either can execute in those contexts, or it explicitly fails it must explicitly fail.

In this way any hook could be placed in any section of the config YAML (obviously assuming the hook supports it).

Thoughts?

**Comment by sds** [comment]
There was a thread back in #420 that explored a similar idea.

The semantics of different hook types are very different at times and it's not clear to me that you can always provide a sensible "reusable" implementation. With pre-push, for example, do staging uncommitted changes make sense? Probably yes, but that's one question we've answered for the pre-commit/pre-push re-use case, and we have many other combinations of hook types we'd need to consider. I don't think this leads down a path of maintainable code.

If the goal is to make it "easy" to reuse pre-commit hooks with pre-push hooks (as your examples discusses), could we achieve this by following the pattern already used in hooks like `BundleInstall`?

https://github.com/sds/overcommit/blob/b4635a3b212b3cbd482f7263fe47c7303a7d684d/lib/overcommit/hook/post_checkout/bundle_install.rb#L10-L12

If you are seeing a path where it is easy to provide this compatibility across hook types, am open to a pull request that demonstrates how to get there without breaking everyone's hooks in the process. I think you will find that the nuances of each hook type make this difficult, and you might as well use the existing pattern we have today.

Regarding your suggestion about running against entire project vs specific files vs a diff: I'm not sure about the diff case (or why that's important), but if we wanted to have `overcommit --run` accept a list of files as arguments, that would be easy to implement, and would be happy to accept a pull request adding support for that case. All you need to do is change [this line](https://github.com/sds/overcommit/blob/b4635a3b212b3cbd482f7263fe47c7303a7d684d/lib/overcommit/hook_context/run_all.rb#L12) to support reading a list of arguments.

I hope I've characterized your ask correctly. If I've missed something, please correct me. Thanks!
