### ISSUE TITLE
Rubocop hook not running correctly

### ISSUE THREAD

**Issue by GenesioValois** [sds/overcommit#701]
When running pre-commit hooks I get this error:
```Analyze with RuboCop........................................[RuboCop] FAILED
Unexpected output: unable to determine line number or type of error/warning for output:
/home/genesio/workspace/phoenix-api/.rubocop.yml: Warning: no department given for Documentation.
/home/genesio/workspace/phoenix-api/.rubocop.yml: Warning: no department given for LineLength.
```

Versions:                                             
ruby 2.5.3
overcommit (0.52.1)
rubocop (0.78.0)

following Rubocop documentation I added this configuration at .rubocop.yml:
```
Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100
```

When I try `rubocop --format=emacs --force-exclusion --display-cop-names` it runs normally, but using overcommit still gets the error

**Comment by sds** [comment]
Did you commit the changes to your `.rubocop.yml`? 

If those changes aren't committed, then Overcommit will stash those changes before running the hooks, and they won't be visible to RuboCop during the run.

Hope that helps!
