### ISSUE TITLE
Rspec only on Modified files?

### ISSUE THREAD

**Issue by quintrino** [sds/overcommit#703]
Is there a way to have the rspec hook run only on modified rspec files? 

Looking at 
https://github.com/sds/overcommit/blob/master/lib/overcommit/hook/pre_push/r_spec.rb

it appears it runs the `rspec` command in it's entirety and doesn't have the option to limit it just to modified rspec files.

**Comment by sds** [comment]
Would welcome a pull request adding functionality to the RSpec pre-push hook to _optionally_ allow running tests only for modified files.

You can use the [`modified_files` helper](https://github.com/sds/overcommit/blob/dc50788d3c6e710231e1efa6bfba9a16e334fae5/lib/overcommit/hook_context/pre_push.rb#L31-L33).
