### ISSUE TITLE
Rubocop 0.80.0 broke integration with overcommit

### ISSUE THREAD

**Issue by ShockwaveNN** [sds/overcommit#704]
Steps to reproduce the problem
```
$ git init
$ cat >.overcommit.yml<< ENDOFFILE
PreCommit:
  RuboCop:
    enabled: true
ENDOFFILE
$ overcommit -i
$ touch test.rb
$ touch .rubocop.yml
$ git add .
$ git commit -m 'init'
$ echo 'p "Hi"' > test.rb
$ git add .
$ git commit -m 'first'
```

Resulting:
```
Running pre-commit hooks
Analyze with RuboCop........................................[RuboCop] FAILED
Unexpected output: unable to determine line number or type of error/warning for output:
 - Style/HashEachMethods
 - Style/HashTransformKeys
 - Style/HashTransformValues

✗ One or more pre-commit hooks failed
```

This warning was introduced in Rubocop 0.80. and marked as feature of RuboCop dev team (see https://github.com/rubocop-hq/rubocop/issues/7731#issuecomment-588097212)

**Comment by szechyjs** [comment]
I was able to work around this by adding `--disable-pending-cops` to `RuboCop.flags` in the config.

**Comment by sds** [comment]
Thank you for the report and the clear workaround. Added as a default in 919350b0a15ebbe7f3cfd058f73e5941ee0e881e.
