### ISSUE TITLE
Inheriting configuration from a dependency gem

### ISSUE THREAD

**Issue by rouaneta** [sds/overcommit#708]
I am working on different repos, shared with different people. We have a default overcommit configuration on a gem. Everytime a change is made to this config, we have to pass it manually to each repo.

It would be really great to be able to inherit configuration from a remote custom configuration so that a same config can be shared across different repos, exactly as it can be done with [RuboCop](https://rubocop.readthedocs.io/en/latest/configuration/#inheriting-configuration-from-a-dependency-gem). In my case, it would be especially interesting to inherit configuration from a dependency gem.

Did you ever think about such a feature ? Does it make sense to you ? Thanks

**Comment by sds** [comment]
Hey @rouaneta, thanks for the suggestion.

Open to such a feature, though one would first need to solve the challenge of adding support for inheriting configurations in the first place, which Overcommit does not support today.

Would welcome a well-tested pull request.

**Comment by baelter** [comment]
Something like travis `import` directive would be nice:
https://docs.travis-ci.com/user/build-config-imports/
