### ISSUE TITLE
`modified_files` and `modified_lines_in_file` on CommitMsg

### ISSUE THREAD

**Issue by Quintasan** [sds/overcommit#726]
I want to create a hook that makes sure that the commit has a longer body describing the changes in detail but only when more than 30 lines are changed across 3 or more files.

Would it be possible for `modified_files` to work the same way as it does in PreCommit hook?

EDIT: I think I would need `modified_lines_in_file` as well for this.

**Comment by sds** [comment]
Happy to merge a pull request adding this functionality!

**Comment by Quintasan** [comment]
Well, I'll try my hand but expect nothing of value 😅
