### ISSUE TITLE
Should we extract `StashUnstagedChanges#initial_commit?` to a module or make it public?

### ISSUE THREAD

**Issue by Quintasan** [sds/overcommit#728]
```
~/overcommit/lib/overcommit/hook/pre_commit/execute_permissions.rb:29: warning: Overcommit::Hook::PreCommit::Base#initial_commit? at ~/.rbenv/versions
/2.6.5/lib/ruby/2.6.0/forwardable.rb:158 forwarding to private method Overcommit::HookContext::PreCommit#initial_commit?
```

_Originally posted by @sds in https://github.com/sds/overcommit/pull/727#issuecomment-696508235_

**Comment by Quintasan** [comment]
@sds We can either:

1. Make `StashUnstashedChanges#initial_commit?` public.
2. Extract it into it's own module and include it where needed.

As you are the maintainer I'm going to defer to your call on this but my personal opinion is that we should extract it to a module on it's own as it's not exclusively related to stashing and unstashing changes.

**Comment by Quintasan** [comment]
@sds I went with the smallest change possible seeing as you didn't respond. We can always extract this particular function to a module later on if really necessary.

**Comment by sds** [comment]
Sorry I missed your suggestion, @Quintasan. Fine with the current approach. Thank you.
