### ISSUE TITLE
`git commit --amend` borked

### ISSUE THREAD

**Issue by liaden** [sds/overcommit#734]
I ran `git commit --amend`. The checks started running, vim opened, I saved with a `:wq`, it finished running. I ended up with almost all my code having been deleted in the commit that happened and then untracked changes left locally.

It seems like there was an issue with files being added to the commit incorrectly with the hooks being ran?

**Comment by SolaWing** [comment]
same problem here. reproduce step:

1. modify .overcommit with a comment, but without add it to git
2. run `git commit`, it's a empty command
3. overcommit still run check, and when finish, almost all files get deleted.

**Comment by jordanstephens** [comment]
Using the repro steps above on an empty repo with the default configuration, I was able to bisect different releases and determine that this bug appeared in version 0.39.0.

I cannot repro using 0.38.0.

**Comment by ngouy** [comment]
same here. Kinda annoing and it make people that don't know git that much pannic x)

**Comment by ngouy** [comment]
https://www.spinics.net/lists/git/msg369520.html

**Comment by deepakmahakale** [comment]
This even happens when you just `git commit` without adding files 

https://github.com/sds/overcommit/issues/751

**Comment by deepakmahakale** [comment]
@ngouy It happens on `0.38.0` as well

**Comment by ngouy** [comment]
it's a git issue ... https://www.spinics.net/lists/git/msg369540.html

**Comment by ngouy** [comment]
it's due to the --quiet option

**Comment by deepakmahakale** [comment]
Yes, got a reply from @sds on this raised issue #751

@ngouy Can we fix this by removing the `--quiet` option?

**Comment by ngouy** [comment]
idk man i'm not a member of this repo. Probably but --quiet seems like it's here for a good reason

I would say the fix should be around unessecary stashing when no files are present
