### ISSUE TITLE
Overcommit swallows non-error output from pronto

### ISSUE THREAD

**Issue by Drowze** [sds/overcommit#754]
Hello guys! 👋 

First of all, thanks for the amazing project! It has helped me a lot through the last few years 😄 

I am now trying to use Overcommit along with PrePush Pronto checks - which is working great for when there's actual errors flagged by pronto. However when there's no _error_ and only _info_ messages, Overcommit does not display them. This is less than ideal as I would love to be able to display some _suggestions_ (which don't fail the action) when the git-hooks are triggered.

I expected that the "quiet" option would be responsible for it, but I couldn't get it to work as desired.

```
⋊> ~/w/o/sts on test-branch ⨯ tail -n15 .overcommit.yml
PrePush:
  Pronto:
    enabled: true
    quiet: false
    description: Analyzing with Pronto (brakeman, fasterer, flay, reek and rubocop)
    flags:
      - run
      - --exit-code
      - --commit=qa
      - --runner
      - brakeman
      - fasterer
      - flay
      - reek
      - rubocop

⋊> ~/w/o/sts on test-branch ⨯ overcommit --install
Installing hooks into /Users/OH-RGIBIN/workspace/org/sts
Successfully installed hooks into /Users/OH-RGIBIN/workspace/org/sts

⋊> ~/w/o/sts on test-branch ⨯ be pronto run --exit-code --commit=qa --runner brakeman rubocop reek flay fasterer
Running Pronto::Brakeman
Running Pronto::Rubocop
Running Pronto::Reek
Running Pronto::Flay
Running Pronto::Fasterer
app/models/shipment.rb:163 I: Calls 'loc.type' 3 times - [DuplicateMethodCall](https://github.com/troessner/reek/blob/v6.0.4/docs/Duplicate-Method-Call.md)
app/models/shipment.rb:163 I: Refers to 'loc' more than self (maybe move it to another class?) - [FeatureEnvy](https://github.com/troessner/reek/blob/v6.0.4/docs/Feature-Envy.md)

⋊> ~/w/o/sts on test-branch ⨯ git push --dry-run origin HEAD
Running pre-push hooks
Analyzing with Pronto (brakeman, fasterer, flay, reek and rubocop)[Pronto] OK

✓ All pre-push hooks passed

To github.com:Org/sts
 * [new branch]        HEAD -> test-branch
```

Is there any workaround for this?

**Comment by sds** [comment]
If you look at how the Pronto hook is implemented, it treats anything that isn't prefixed with `E:` as a warning:
https://github.com/sds/overcommit/blob/7d94fa55a74ceea705645d565a34ecefaca08ea5/lib/overcommit/hook/shared/pronto.rb#L7

Therefore these messages should be getting shown. I'm personally not familiar with `pronto`, so it might be worth reaching out to the author of #488 if you'd like some more insight. Perhaps there is something wrong with the regex in:
https://github.com/sds/overcommit/blob/7d94fa55a74ceea705645d565a34ecefaca08ea5/lib/overcommit/hook/shared/pronto.rb#L16

Appreciate you digging in to investigate. I won't personally be digging further unless there's a clear issue we can point to within Overcommit itself.

**Comment by Drowze** [comment]
Thank you for the quick answer @sds! Those leads are very helpful already; I'll try to dig a bit further when I have the time.
