### ISSUE TITLE
Can you cut a new release? (last one was May 3rd, 2022)

### ISSUE THREAD

**Issue by jethrodaniel** [sds/overcommit#806]
Last release was a _while_ ago:
- https://rubygems.org/gems/overcommit/versions/0.59.1

But we've had [some PRs merged since then](https://github.com/sds/overcommit/compare/v0.59.1...master) - @sds can you (or someone else who has access), cut a new release?

Also, I noticed that while there is a rubygem release and git tag for v0.59.1, there isn't a Github release for it, we might want to add that eventually for visibility purposes - last release on GH is https://github.com/sds/overcommit/releases/tag/v0.59.0

Btw, thanks for the great project! 🎉

**Comment by sds** [comment]
[0.60.0](https://github.com/sds/overcommit/releases/tag/v0.60.0) has been released.
