### ISSUE TITLE
GitHub Actions deprecated node12

### ISSUE THREAD

**Issue by fulf** [sds/overcommit#834]
GitHub Actions workflow currently gives the following warning:
> - Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2, coverallsapp/github-action@master. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
> - The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

Solutions:
- update `actions/checkout@v2` to `actions/checkout@v4`
- update `coverallsapp/github-action@master` to `coverallsapp/github-action@v2`

**Comment by sds** [comment]
Thanks for the update!
